###
GET http://localhost:5047/catalog

###
GET http://localhost:5047/catalog/0

###
POST http://localhost:5047/catalog
Content-Type: application/json

{
  "name": "Shoes",
  "description": "Ohio State shoes",
  "brand": "Nike",
  "price": 129.99
}

###
POST http://localhost:5047/catalog/1/ratings
Content-Type: application/json

{
  "stars": 5,
  "userName": "Cameron",
  "review": "Great shoes"
}

###
PUT http://localhost:5047/catalog/1
Content-Type: application/json

{
  "name": "Updated Shoes",
  "description": "Updated description",
  "brand": "Nike",
  "price": 149.99
}

###
DELETE http://localhost:5047/catalog/1

###
curl --request POST \
  --url https://dev-lej4lxrlupd1kl8m.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{
    "client_id":"Y7JO4hQIEkBtxxQ2SAJQtJX2d0EKwcT6",
    "client_secret":"k4Us5S9l-8lkYiLxURURKuZ-dYscPh2f-WGG2bRP_or96hDbXwMoMTbuJHhz9Wuv",
    "audience":"https://digital-shopping-center",
    "grant_type":"client_credentials"
  }'